language: python
python:
  - "2.7"
install:
  - pip install flake8
script:
  - chmod +x manage.py
  - pip install -r requirements.txt
  - ./manage.py syncdb --noinput
  - ./manage.py loaddata sites
  - ./manage.py validate
  - flake8 ppb
